--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Client generated by Zap v0.6.27 (https://github.com/red-blox/zap)

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["ZAP"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of ZAP, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["ZAP"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["ZAP"] = "0.6.27"

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
	})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		UnreliableComponentNetworkServer = table.freeze({
			Fire = noop
		}),
		UnreliableComponentNetworkClient = table.freeze({
			On = noop
		}),
		ThrowablesServiceCreate = table.freeze({
			SetCallback = noop
		}),
		Start = table.freeze({
			Fire = noop
		}),
		SpawnRequest = table.freeze({
			Fire = noop
		}),
		ShopServiceChangeSelected = table.freeze({
			Fire = noop
		}),
		ShopServiceBuyConfirm = table.freeze({
			SetCallback = noop
		}),
		ShopServiceBuy = table.freeze({
			Fire = noop
		}),
		ShopItemPayoutComplete = table.freeze({
			SetCallback = noop
		}),
		SetRagdoll = table.freeze({
			SetCallback = noop
		}),
		ServerLookVectorReplicated = table.freeze({
			SetCallback = noop
		}),
		RoundStatsComponentReplicator = table.freeze({
			On = noop
		}),
		RespondPlayersInHitbox = table.freeze({
			Fire = noop
		}),
		RequestPlayersInHitbox = table.freeze({
			SetCallback = noop
		}),
		ReplicateItemServer = table.freeze({
			SetCallback = noop
		}),
		ReliableComponentNetworkServer = table.freeze({
			Fire = noop
		}),
		ReliableComponentNetworkClient = table.freeze({
			On = noop
		}),
		RebuildRoleConfigClient = table.freeze({
			SetCallback = noop
		}),
		PointsAwarded = table.freeze({
			On = noop
		}),
		PlayerDied = table.freeze({
			On = noop
		}),
		PlayerActionApplied = table.freeze({
			SetCallback = noop
		}),
		OnServerInventoryToggle = table.freeze({
			SetCallback = noop
		}),
		ObjectivesChanged = table.freeze({
			SetCallback = noop
		}),
		MatchServiceStartLMS = table.freeze({
			On = noop
		}),
		MatchServiceSetPreparing = table.freeze({
			SetCallback = noop
		}),
		MatchServiceSetMatchState = table.freeze({
			SetCallback = noop
		}),
		MatchServiceSetMap = table.freeze({
			On = noop
		}),
		MatchServiceCountdownChanged = table.freeze({
			SetCallback = noop
		}),
		LoadedConfirmed = table.freeze({
			SetCallback = noop
		}),
		Loaded = table.freeze({
			Fire = noop
		}),
		InventoryComponentDropItemServer = table.freeze({
			Fire = noop
		}),
		HideoutLeavePrompt = table.freeze({
			Fire = noop
		}),
		Dispatch = table.freeze({
			SetCallback = noop
		}),
		DespawnRequest = table.freeze({
			Fire = noop
		}),
		DamageTaken = table.freeze({
			On = noop
		}),
		ComponentReplicatorClient = table.freeze({
			SetCallback = noop
		}),
		ClientTRStateChanged = table.freeze({
			Fire = noop
		}),
		ClientSettingSaveRequest = table.freeze({
			Fire = noop
		}),
		ClientLookVectorChanged = table.freeze({
			Fire = noop
		}),
		ClientLanded = table.freeze({
			Fire = noop
		}),
		ClientFallStarted = table.freeze({
			Fire = noop
		}),
		ClientChaseStateChanged = table.freeze({
			Fire = noop
		}),
		CharacterSyncFromServer = table.freeze({
			SetCallback = noop
		}),
		CharacterSyncFromClient = table.freeze({
			Fire = noop
		}),
		ChangeStamina = table.freeze({
			On = noop
		}),
		ApplyImpulse = table.freeze({
			SetCallback = noop
		}),
	}) :: Events
end
if RunService:IsServer() then
	error("Cannot use the client module on the server!")
end
local remotes = ReplicatedStorage:WaitForChild("ZAP")

local reliable = remotes:WaitForChild("ZAP_RELIABLE")
assert(reliable:IsA("RemoteEvent"), "Expected ZAP_RELIABLE to be a RemoteEvent")

local unreliable = { remotes:WaitForChild("ZAP_UNRELIABLE_0"), remotes:WaitForChild("ZAP_UNRELIABLE_1"), remotes:WaitForChild("ZAP_UNRELIABLE_2"), remotes:WaitForChild("ZAP_UNRELIABLE_3") }
assert(unreliable[1]:IsA("UnreliableRemoteEvent"), "Expected ZAP_UNRELIABLE_0 to be an UnreliableRemoteEvent")
assert(unreliable[2]:IsA("UnreliableRemoteEvent"), "Expected ZAP_UNRELIABLE_1 to be an UnreliableRemoteEvent")
assert(unreliable[3]:IsA("UnreliableRemoteEvent"), "Expected ZAP_UNRELIABLE_2 to be an UnreliableRemoteEvent")
assert(unreliable[4]:IsA("UnreliableRemoteEvent"), "Expected ZAP_UNRELIABLE_3 to be an UnreliableRemoteEvent")
export type HitboxType = ("Box" | "Sphere")
export type ChangeMethod = ("Set" | "Multiply" | "Increment")
export type ShopBuyType = ("Item" | "Character" | "Skin")

local function SendEvents()
	if outgoing_used ~= 0 then
		local buff = buffer.create(outgoing_used)
		buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)

		reliable:FireServer(buff, outgoing_inst)

		outgoing_buff = buffer.create(64)
		outgoing_used = 0
		outgoing_size = 64
		table.clear(outgoing_inst)
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(24)
local reliable_event_queue: { [number]: { any } } = table.create(24)
local unreliable_events = table.create(4)
local unreliable_event_queue: { [number]: { any } } = table.create(4)
unreliable_events[0] = {}
unreliable_event_queue[0] = {}
reliable_event_queue[11] = {}
reliable_event_queue[21] = {}
reliable_event_queue[22] = {}
reliable_event_queue[3] = {}
unreliable_event_queue[3] = {}
reliable_events[23] = {}
reliable_event_queue[23] = {}
reliable_event_queue[8] = {}
reliable_event_queue[10] = {}
reliable_events[6] = {}
reliable_event_queue[6] = {}
reliable_event_queue[2] = {}
reliable_events[14] = {}
reliable_event_queue[14] = {}
reliable_events[13] = {}
reliable_event_queue[13] = {}
unreliable_event_queue[1] = {}
reliable_event_queue[9] = {}
reliable_event_queue[20] = {}
reliable_events[15] = {}
reliable_event_queue[15] = {}
reliable_event_queue[19] = {}
reliable_event_queue[17] = {}
reliable_events[16] = {}
reliable_event_queue[16] = {}
reliable_event_queue[18] = {}
reliable_event_queue[0] = {}
reliable_event_queue[1] = {}
reliable_events[12] = {}
reliable_event_queue[12] = {}
reliable_event_queue[7] = {}
unreliable_event_queue[2] = {}
reliable_events[5] = {}
reliable_event_queue[5] = {}
reliable_event_queue[4] = {}
reliable.OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 11 then
			local value
			local bool_1 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			incoming_ipos = incoming_ipos + 1
			value["instance"] = incoming_inst[incoming_ipos]
			assert(value["instance"] ~= nil, "received instance is nil!")
			assert(value["instance"]:IsA("Tool"), "received instance is not of the Tool class!")
			value["userData"] = {  }
			value["userData"]["Origin"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			value["userData"]["Strength"] = buffer.readf64(incoming_buff, read(8))
			value["userData"]["Direction"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			if bit32.btest(bool_1, 0b0000000000000001) then
				incoming_ipos = incoming_ipos + 1
				value["userData"]["Performer"] = incoming_inst[incoming_ipos]
				assert(value["userData"]["Performer"] == nil or value["userData"]["Performer"]:IsA("Player"), "received instance is not of the Player class!")
			else
				value["userData"]["Performer"] = nil
			end
			if reliable_events[11] then
				task.spawn(reliable_events[11], value)
			else
				table.insert(reliable_event_queue[11], value)
				if #reliable_event_queue[11] > 64 then
					warn(`[ZAP] {#reliable_event_queue[11]} events in queue for ThrowablesServiceCreate. Did you forget to attach a listener?`)
				end
			end
		elseif id == 21 then
			local value
			local bool_2 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			if bit32.btest(bool_2, 0b0000000000000001) then
				value["Type"] = "Item"
			elseif bit32.btest(bool_2, 0b0000000000000010) then
				value["Type"] = "Character"
			elseif bit32.btest(bool_2, 0b0000000000000100) then
				value["Type"] = "Skin"
			end
			value["Data"] = {  }
			local len_1 = buffer.readu16(incoming_buff, read(2))
			value["Data"]["Character"] = buffer.readstring(incoming_buff, read(len_1), len_1)
			local len_2 = buffer.readu16(incoming_buff, read(2))
			value["Data"]["Skin"] = buffer.readstring(incoming_buff, read(len_2), len_2)
			local len_3 = buffer.readu16(incoming_buff, read(2))
			value["Data"]["ItemName"] = buffer.readstring(incoming_buff, read(len_3), len_3)
			value["Data"]["Amount"] = buffer.readu8(incoming_buff, read(1))
			if reliable_events[21] then
				task.spawn(reliable_events[21], value)
			else
				table.insert(reliable_event_queue[21], value)
				if #reliable_event_queue[21] > 64 then
					warn(`[ZAP] {#reliable_event_queue[21]} events in queue for ShopServiceBuyConfirm. Did you forget to attach a listener?`)
				end
			end
		elseif id == 22 then
			local value
			value = {  }
			local len_4 = buffer.readu16(incoming_buff, read(2))
			value["Items"] = table.create(len_4)
			for i_1 = 1, len_4 do
				local val_1
				local len_5 = buffer.readu16(incoming_buff, read(2))
				val_1 = buffer.readstring(incoming_buff, read(len_5), len_5)
				value["Items"][i_1] = val_1
			end
			if reliable_events[22] then
				task.spawn(reliable_events[22], value)
			else
				table.insert(reliable_event_queue[22], value)
				if #reliable_event_queue[22] > 64 then
					warn(`[ZAP] {#reliable_event_queue[22]} events in queue for ShopItemPayoutComplete. Did you forget to attach a listener?`)
				end
			end
		elseif id == 3 then
			local value
			local bool_3 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["toggle"] = bit32.btest(bool_3, 0b0000000000000001)
			if bit32.btest(bool_3, 0b0000000000000010) then
				incoming_ipos = incoming_ipos + 1
				value["model"] = incoming_inst[incoming_ipos]
			else
				value["model"] = nil
			end
			if reliable_events[3] then
				task.spawn(reliable_events[3], value)
			else
				table.insert(reliable_event_queue[3], value)
				if #reliable_event_queue[3] > 64 then
					warn(`[ZAP] {#reliable_event_queue[3]} events in queue for SetRagdoll. Did you forget to attach a listener?`)
				end
			end
		elseif id == 23 then
			local value
			local bool_4 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			if not bit32.btest(bool_4, 0b0000000000000001) then
				for _ = 1, buffer.readu16(incoming_buff, read(2)) + 1 do
					local bool_5 = buffer.readu8(incoming_buff, read(1))
					local key_1
					local val_2
					incoming_ipos = incoming_ipos + 1
					key_1 = incoming_inst[incoming_ipos]
					assert(key_1 ~= nil, "received instance is nil!")
					assert(key_1:IsA("Player"), "received instance is not of the Player class!")
					if bit32.btest(bool_5, 0b0000000000000001) then
						incoming_ipos = incoming_ipos + 1
						val_2 = incoming_inst[incoming_ipos]
					else
						val_2 = nil
					end
					value[key_1] = val_2
				end
			end
			if reliable_events[23][1] then
				for _, cb in reliable_events[23] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[23], value)
				if #reliable_event_queue[23] > 64 then
					warn(`[ZAP] {#reliable_event_queue[23]} events in queue for RoundStatsComponentReplicator. Did you forget to attach a listener?`)
				end
			end
		elseif id == 8 then
			local value
			local bool_6 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			if bit32.btest(bool_6, 0b0000000000000001) then
				value["Type"] = "Box"
			else
				value["Type"] = "Sphere"
			end
			if bit32.btest(bool_6, 0b0000000000000010) then
				incoming_ipos = incoming_ipos + 1
				value["Size"] = incoming_inst[incoming_ipos]
			else
				value["Size"] = nil
			end
			value["Offset"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			if reliable_events[8] then
				task.spawn(reliable_events[8], value)
			else
				table.insert(reliable_event_queue[8], value)
				if #reliable_event_queue[8] > 64 then
					warn(`[ZAP] {#reliable_event_queue[8]} events in queue for RequestPlayersInHitbox. Did you forget to attach a listener?`)
				end
			end
		elseif id == 10 then
			local value
			local bool_7 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			incoming_ipos = incoming_ipos + 1
			value["instance"] = incoming_inst[incoming_ipos]
			assert(value["instance"] ~= nil, "received instance is nil!")
			assert(value["instance"]:IsA("Tool"), "received instance is not of the Tool class!")
			value["destroyed"] = bit32.btest(bool_7, 0b0000000000000001)
			local len_6 = buffer.readu16(incoming_buff, read(2))
			value["constructor"] = buffer.readstring(incoming_buff, read(len_6), len_6)
			if reliable_events[10] then
				task.spawn(reliable_events[10], value)
			else
				table.insert(reliable_event_queue[10], value)
				if #reliable_event_queue[10] > 64 then
					warn(`[ZAP] {#reliable_event_queue[10]} events in queue for ReplicateItemServer. Did you forget to attach a listener?`)
				end
			end
		elseif id == 6 then
			local value
			local bool_8 = buffer.readu8(incoming_buff, read(1))
			if bit32.btest(bool_8, 0b0000000000000001) then
				incoming_ipos = incoming_ipos + 1
				value = incoming_inst[incoming_ipos]
			else
				value = nil
			end
			if reliable_events[6][1] then
				for _, cb in reliable_events[6] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[6], value)
				if #reliable_event_queue[6] > 64 then
					warn(`[ZAP] {#reliable_event_queue[6]} events in queue for ReliableComponentNetworkClient. Did you forget to attach a listener?`)
				end
			end
		elseif id == 2 then
			local value
			local bool_9 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			incoming_ipos = incoming_ipos + 1
			value["player"] = incoming_inst[incoming_ipos]
			assert(value["player"] ~= nil, "received instance is nil!")
			assert(value["player"]:IsA("Player"), "received instance is not of the Player class!")
			value["params"] = {  }
			local len_7 = buffer.readu16(incoming_buff, read(2))
			value["params"]["Role"] = buffer.readstring(incoming_buff, read(len_7), len_7)
			if bit32.btest(bool_9, 0b0000000000000001) then
				local len_8 = buffer.readu16(incoming_buff, read(2))
				value["params"]["Skin"] = buffer.readstring(incoming_buff, read(len_8), len_8)
			else
				value["params"]["Skin"] = nil
			end
			if bit32.btest(bool_9, 0b0000000000000010) then
				local len_9 = buffer.readu16(incoming_buff, read(2))
				value["params"]["Character"] = buffer.readstring(incoming_buff, read(len_9), len_9)
			else
				value["params"]["Character"] = nil
			end
			if reliable_events[2] then
				task.spawn(reliable_events[2], value)
			else
				table.insert(reliable_event_queue[2], value)
				if #reliable_event_queue[2] > 64 then
					warn(`[ZAP] {#reliable_event_queue[2]} events in queue for RebuildRoleConfigClient. Did you forget to attach a listener?`)
				end
			end
		elseif id == 14 then
			local value
			local bool_10 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["amount"] = buffer.readu32(incoming_buff, read(4))
			if bit32.btest(bool_10, 0b0000000000000001) then
				value["actionId"] = buffer.readu32(incoming_buff, read(4))
			else
				value["actionId"] = nil
			end
			if bit32.btest(bool_10, 0b0000000000000010) then
				local len_10 = buffer.readu16(incoming_buff, read(2))
				value["message"] = buffer.readstring(incoming_buff, read(len_10), len_10)
			else
				value["message"] = nil
			end
			if reliable_events[14][1] then
				for _, cb in reliable_events[14] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[14], value)
				if #reliable_event_queue[14] > 64 then
					warn(`[ZAP] {#reliable_event_queue[14]} events in queue for PointsAwarded. Did you forget to attach a listener?`)
				end
			end
		elseif id == 13 then
			local value
			local bool_11 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			incoming_ipos = incoming_ipos + 1
			value["player"] = incoming_inst[incoming_ipos]
			assert(value["player"] ~= nil, "received instance is nil!")
			assert(value["player"]:IsA("Player"), "received instance is not of the Player class!")
			if bit32.btest(bool_11, 0b0000000000000001) then
				local len_11 = buffer.readu16(incoming_buff, read(2))
				value["killers"] = table.create(len_11)
				for i_2 = 1, len_11 do
					local val_3
					incoming_ipos = incoming_ipos + 1
					val_3 = incoming_inst[incoming_ipos]
					assert(val_3 ~= nil, "received instance is nil!")
					assert(val_3:IsA("Player"), "received instance is not of the Player class!")
					value["killers"][i_2] = val_3
				end
			else
				value["killers"] = nil
			end
			if reliable_events[13][1] then
				for _, cb in reliable_events[13] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[13], value)
				if #reliable_event_queue[13] > 64 then
					warn(`[ZAP] {#reliable_event_queue[13]} events in queue for PlayerDied. Did you forget to attach a listener?`)
				end
			end
		elseif id == 9 then
			local value
			local bool_12 = buffer.readu8(incoming_buff, read(1))
			value = bit32.btest(bool_12, 0b0000000000000001)
			if reliable_events[9] then
				task.spawn(reliable_events[9], value)
			else
				table.insert(reliable_event_queue[9], value)
				if #reliable_event_queue[9] > 64 then
					warn(`[ZAP] {#reliable_event_queue[9]} events in queue for OnServerInventoryToggle. Did you forget to attach a listener?`)
				end
			end
		elseif id == 20 then
			local value
			value = {  }
			value["amount"] = buffer.readu32(incoming_buff, read(4))
			value["solvedAmount"] = buffer.readu32(incoming_buff, read(4))
			if reliable_events[20] then
				task.spawn(reliable_events[20], value)
			else
				table.insert(reliable_event_queue[20], value)
				if #reliable_event_queue[20] > 64 then
					warn(`[ZAP] {#reliable_event_queue[20]} events in queue for ObjectivesChanged. Did you forget to attach a listener?`)
				end
			end
		elseif id == 15 then
			local value
			local bool_13 = buffer.readu8(incoming_buff, read(1))
			if bit32.btest(bool_13, 0b0000000000000001) then
				incoming_ipos = incoming_ipos + 1
				value = incoming_inst[incoming_ipos]
			else
				value = nil
			end
			if reliable_events[15][1] then
				for _, cb in reliable_events[15] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[15], value)
				if #reliable_event_queue[15] > 64 then
					warn(`[ZAP] {#reliable_event_queue[15]} events in queue for MatchServiceStartLMS. Did you forget to attach a listener?`)
				end
			end
		elseif id == 19 then
			local value
			local bool_14 = buffer.readu8(incoming_buff, read(1))
			value = bit32.btest(bool_14, 0b0000000000000001)
			if reliable_events[19] then
				task.spawn(reliable_events[19], value)
			else
				table.insert(reliable_event_queue[19], value)
				if #reliable_event_queue[19] > 64 then
					warn(`[ZAP] {#reliable_event_queue[19]} events in queue for MatchServiceSetPreparing. Did you forget to attach a listener?`)
				end
			end
		elseif id == 17 then
			local value
			local bool_15 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			local len_12 = buffer.readu16(incoming_buff, read(2))
			value["name"] = buffer.readstring(incoming_buff, read(len_12), len_12)
			value["ended"] = bit32.btest(bool_15, 0b0000000000000001)
			value["duration"] = buffer.readu32(incoming_buff, read(4))
			if reliable_events[17] then
				task.spawn(reliable_events[17], value)
			else
				table.insert(reliable_event_queue[17], value)
				if #reliable_event_queue[17] > 64 then
					warn(`[ZAP] {#reliable_event_queue[17]} events in queue for MatchServiceSetMatchState. Did you forget to attach a listener?`)
				end
			end
		elseif id == 16 then
			local value
			local len_13 = buffer.readu16(incoming_buff, read(2))
			value = buffer.readstring(incoming_buff, read(len_13), len_13)
			if reliable_events[16][1] then
				for _, cb in reliable_events[16] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[16], value)
				if #reliable_event_queue[16] > 64 then
					warn(`[ZAP] {#reliable_event_queue[16]} events in queue for MatchServiceSetMap. Did you forget to attach a listener?`)
				end
			end
		elseif id == 18 then
			local value
			local bool_16 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			value["value"] = buffer.readu32(incoming_buff, read(4))
			if bit32.btest(bool_16, 0b0000000000000001) then
				local len_14 = buffer.readu16(incoming_buff, read(2))
				value["reason"] = buffer.readstring(incoming_buff, read(len_14), len_14)
			else
				value["reason"] = nil
			end
			if reliable_events[18] then
				task.spawn(reliable_events[18], value)
			else
				table.insert(reliable_event_queue[18], value)
				if #reliable_event_queue[18] > 64 then
					warn(`[ZAP] {#reliable_event_queue[18]} events in queue for MatchServiceCountdownChanged. Did you forget to attach a listener?`)
				end
			end
		elseif id == 0 then
			local value
			local bool_17 = buffer.readu8(incoming_buff, read(1))
			if bit32.btest(bool_17, 0b0000000000000001) then
				incoming_ipos = incoming_ipos + 1
				value = incoming_inst[incoming_ipos]
			else
				value = nil
			end
			if reliable_events[0] then
				task.spawn(reliable_events[0], value)
			else
				table.insert(reliable_event_queue[0], value)
				if #reliable_event_queue[0] > 64 then
					warn(`[ZAP] {#reliable_event_queue[0]} events in queue for LoadedConfirmed. Did you forget to attach a listener?`)
				end
			end
		elseif id == 1 then
			local value
			local len_15 = buffer.readu16(incoming_buff, read(2))
			value = table.create(len_15)
			for i_3 = 1, len_15 do
				local val_4
				val_4 = {  }
				local len_16 = buffer.readu16(incoming_buff, read(2))
				val_4["name"] = buffer.readstring(incoming_buff, read(len_16), len_16)
				local len_17 = buffer.readu16(incoming_buff, read(2))
				val_4["arguments"] = table.create(len_17)
				for i_4 = 1, len_17 do
					local bool_18 = buffer.readu8(incoming_buff, read(1))
					local val_5
					if bit32.btest(bool_18, 0b0000000000000001) then
						incoming_ipos = incoming_ipos + 1
						val_5 = incoming_inst[incoming_ipos]
					else
						val_5 = nil
					end
					val_4["arguments"][i_4] = val_5
				end
				value[i_3] = val_4
			end
			if reliable_events[1] then
				task.spawn(reliable_events[1], value)
			else
				table.insert(reliable_event_queue[1], value)
				if #reliable_event_queue[1] > 64 then
					warn(`[ZAP] {#reliable_event_queue[1]} events in queue for Dispatch. Did you forget to attach a listener?`)
				end
			end
		elseif id == 12 then
			local value
			local bool_19 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			incoming_ipos = incoming_ipos + 1
			value["player"] = incoming_inst[incoming_ipos]
			assert(value["player"] ~= nil, "received instance is nil!")
			assert(value["player"]:IsA("Player"), "received instance is not of the Player class!")
			if bit32.btest(bool_19, 0b0000000000000001) then
				incoming_ipos = incoming_ipos + 1
				value["damager"] = incoming_inst[incoming_ipos]
				assert(value["damager"] == nil or value["damager"]:IsA("Player"), "received instance is not of the Player class!")
			else
				value["damager"] = nil
			end
			if bit32.btest(bool_19, 0b0000000000000010) then
				value["origin"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			else
				value["origin"] = nil
			end
			value["damage"] = buffer.readi8(incoming_buff, read(1))
			if bit32.btest(bool_19, 0b0000000000000100) then
				local len_18 = buffer.readu16(incoming_buff, read(2))
				value["source"] = buffer.readstring(incoming_buff, read(len_18), len_18)
			else
				value["source"] = nil
			end
			if reliable_events[12][1] then
				for _, cb in reliable_events[12] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[12], value)
				if #reliable_event_queue[12] > 64 then
					warn(`[ZAP] {#reliable_event_queue[12]} events in queue for DamageTaken. Did you forget to attach a listener?`)
				end
			end
		elseif id == 7 then
			local value
			local bool_20 = buffer.readu8(incoming_buff, read(1))
			if bit32.btest(bool_20, 0b0000000000000001) then
				incoming_ipos = incoming_ipos + 1
				value = incoming_inst[incoming_ipos]
			else
				value = nil
			end
			if reliable_events[7] then
				task.spawn(reliable_events[7], value)
			else
				table.insert(reliable_event_queue[7], value)
				if #reliable_event_queue[7] > 64 then
					warn(`[ZAP] {#reliable_event_queue[7]} events in queue for ComponentReplicatorClient. Did you forget to attach a listener?`)
				end
			end
		elseif id == 5 then
			local value
			local bool_21 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			if bit32.btest(bool_21, 0b0000000000000001) then
				value["method"] = "Set"
			elseif bit32.btest(bool_21, 0b0000000000000010) then
				value["method"] = "Multiply"
			elseif bit32.btest(bool_21, 0b0000000000000100) then
				value["method"] = "Increment"
			end
			value["value"] = buffer.readf64(incoming_buff, read(8))
			if reliable_events[5][1] then
				for _, cb in reliable_events[5] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[5], value)
				if #reliable_event_queue[5] > 64 then
					warn(`[ZAP] {#reliable_event_queue[5]} events in queue for ChangeStamina. Did you forget to attach a listener?`)
				end
			end
		elseif id == 4 then
			local value
			local bool_22 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			incoming_ipos = incoming_ipos + 1
			value["part"] = incoming_inst[incoming_ipos]
			assert(value["part"] ~= nil, "received instance is nil!")
			value["impulse"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			if bit32.btest(bool_22, 0b0000000000000001) then
				value["isAngular"] = bit32.btest(bool_22, 0b0000000000000010)
			else
				value["isAngular"] = nil
			end
			if reliable_events[4] then
				task.spawn(reliable_events[4], value)
			else
				table.insert(reliable_event_queue[4], value)
				if #reliable_event_queue[4] > 64 then
					warn(`[ZAP] {#reliable_event_queue[4]} events in queue for ApplyImpulse. Did you forget to attach a listener?`)
				end
			end
		else
			error("Unknown event id")
		end
	end
end)
unreliable[1].OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local value
	local bool_23 = buffer.readu8(incoming_buff, read(1))
	if bit32.btest(bool_23, 0b0000000000000001) then
		incoming_ipos = incoming_ipos + 1
		value = incoming_inst[incoming_ipos]
	else
		value = nil
	end
	if unreliable_events[0][1] then
		for _, cb in unreliable_events[0] do
			task.spawn(cb, value)
		end
	else
		table.insert(unreliable_event_queue[0], value)
		if #unreliable_event_queue[0] > 64 then
			warn(`[ZAP] {#unreliable_event_queue[0]} events in queue for UnreliableComponentNetworkClient. Did you forget to attach a listener?`)
		end
	end
end)
unreliable[4].OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local value
	value = {  }
	incoming_ipos = incoming_ipos + 1
	value["player"] = incoming_inst[incoming_ipos]
	assert(value["player"] ~= nil, "received instance is nil!")
	assert(value["player"]:IsA("Player"), "received instance is not of the Player class!")
	value["lookDirection"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
	local len_19 = buffer.readu16(incoming_buff, read(2))
	value["componentName"] = buffer.readstring(incoming_buff, read(len_19), len_19)
	if unreliable_events[3] then
		task.spawn(unreliable_events[3], value)
	else
		table.insert(unreliable_event_queue[3], value)
		if #unreliable_event_queue[3] > 64 then
			warn(`[ZAP] {#unreliable_event_queue[3]} events in queue for ServerLookVectorReplicated. Did you forget to attach a listener?`)
		end
	end
end)
unreliable[2].OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local value
	local len_20 = buffer.readu16(incoming_buff, read(2))
	value = buffer.readstring(incoming_buff, read(len_20), len_20)
	if unreliable_events[1] then
		task.spawn(unreliable_events[1], value)
	else
		table.insert(unreliable_event_queue[1], value)
		if #unreliable_event_queue[1] > 64 then
			warn(`[ZAP] {#unreliable_event_queue[1]} events in queue for PlayerActionApplied. Did you forget to attach a listener?`)
		end
	end
end)
unreliable[3].OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local value
	value = {  }
	incoming_ipos = incoming_ipos + 1
	value["player"] = incoming_inst[incoming_ipos]
	assert(value["player"] ~= nil, "received instance is nil!")
	assert(value["player"]:IsA("Player"), "received instance is not of the Player class!")
	incoming_ipos = incoming_ipos + 1
	value["part"] = incoming_inst[incoming_ipos]
	assert(value["part"] ~= nil, "received instance is nil!")
	assert(value["part"]:IsA("Part"), "received instance is not of the Part class!")
	local pos_1 = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
	local axisangle_1 = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
	local angle_1 = axisangle_1.Magnitude
	if angle_1 ~= 0 then
		value["cframe"] = CFrame.fromAxisAngle(axisangle_1, angle_1) + pos_1
	else
		value["cframe"] = CFrame.new(pos_1)
	end
	if unreliable_events[2] then
		task.spawn(unreliable_events[2], value)
	else
		table.insert(unreliable_event_queue[2], value)
		if #unreliable_event_queue[2] > 64 then
			warn(`[ZAP] {#unreliable_event_queue[2]} events in queue for CharacterSyncFromServer. Did you forget to attach a listener?`)
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	UnreliableComponentNetworkServer = {
		Fire = function(Value: ((unknown)))
			local saved = save()
			load_empty()
			local bool_24 = 0
			local bool_24_pos_1 = alloc(1)
			if Value ~= nil then
				bool_24 = bit32.bor(bool_24, 0b0000000000000001)
				table.insert(outgoing_inst, Value)
			end
			buffer.writeu8(outgoing_buff, bool_24_pos_1, bool_24)
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			unreliable[1]:FireServer(buff, outgoing_inst)
			load(saved)
		end,
	},
	UnreliableComponentNetworkClient = {
		On = function(Callback: (Value: ((unknown))) -> ())
			table.insert(unreliable_events[0], Callback)
			for _, value in unreliable_event_queue[0] do
				task.spawn(Callback, value)
			end
			unreliable_event_queue[0] = {}
			return function()
				table.remove(unreliable_events[0], table.find(unreliable_events[0], Callback))
			end
		end,
	},
	ThrowablesServiceCreate = {
		SetCallback = function(Callback: (Value: ({
			["instance"]: (Tool),
			["userData"]: ({
				["Origin"]: (Vector3),
				["Strength"]: (number),
				["Direction"]: (Vector3),
				["Performer"]: ((Player)?),
			}),
			})) -> ()): () -> ()
			reliable_events[11] = Callback
			for _, value in reliable_event_queue[11] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[11] = {}
			return function()
				reliable_events[11] = nil
			end
		end,
	},
	Start = {
		Fire = function()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
		end,
	},
	SpawnRequest = {
		Fire = function(Value: ((unknown)))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			local bool_25 = 0
			local bool_25_pos_1 = alloc(1)
			if Value ~= nil then
				bool_25 = bit32.bor(bool_25, 0b0000000000000001)
				table.insert(outgoing_inst, Value)
			end
			buffer.writeu8(outgoing_buff, bool_25_pos_1, bool_25)
		end,
	},
	ShopServiceChangeSelected = {
		Fire = function(Value: ({
			["Character"]: (string),
			["Skin"]: (string),
			}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 14)
			local len_21 = #Value["Character"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_21)
			alloc(len_21)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["Character"], len_21)
			local len_22 = #Value["Skin"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_22)
			alloc(len_22)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["Skin"], len_22)
		end,
	},
	ShopServiceBuyConfirm = {
		SetCallback = function(Callback: (Value: ({
			["Type"]: ("Item" | "Character" | "Skin"),
			["Data"]: ({
				["Character"]: (string),
				["Skin"]: (string),
				["ItemName"]: (string),
				["Amount"]: (number),
			}),
			})) -> ()): () -> ()
			reliable_events[21] = Callback
			for _, value in reliable_event_queue[21] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[21] = {}
			return function()
				reliable_events[21] = nil
			end
		end,
	},
	ShopServiceBuy = {
		Fire = function(Value: ({
			["Type"]: ("Item" | "Character" | "Skin"),
			["Data"]: ({
				["Character"]: (string),
				["Skin"]: (string),
				["ItemName"]: (string),
			}),
			}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 13)
			local bool_26 = 0
			local bool_26_pos_1 = alloc(1)
			if Value["Type"] == "Item" then
				bool_26 = bit32.bor(bool_26, 0b0000000000000001)
			elseif Value["Type"] == "Character" then
				bool_26 = bit32.bor(bool_26, 0b0000000000000010)
			elseif Value["Type"] == "Skin" then
				bool_26 = bit32.bor(bool_26, 0b0000000000000100)
			else
				error("Invalid enumerator")
			end
			local len_23 = #Value["Data"]["Character"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_23)
			alloc(len_23)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["Data"]["Character"], len_23)
			local len_24 = #Value["Data"]["Skin"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_24)
			alloc(len_24)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["Data"]["Skin"], len_24)
			local len_25 = #Value["Data"]["ItemName"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_25)
			alloc(len_25)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["Data"]["ItemName"], len_25)
			buffer.writeu8(outgoing_buff, bool_26_pos_1, bool_26)
		end,
	},
	ShopItemPayoutComplete = {
		SetCallback = function(Callback: (Value: ({
			["Items"]: ({ (string) }),
			})) -> ()): () -> ()
			reliable_events[22] = Callback
			for _, value in reliable_event_queue[22] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[22] = {}
			return function()
				reliable_events[22] = nil
			end
		end,
	},
	SetRagdoll = {
		SetCallback = function(Callback: (Value: ({
			["toggle"]: (boolean),
			["model"]: ((Instance)?),
			})) -> ()): () -> ()
			reliable_events[3] = Callback
			for _, value in reliable_event_queue[3] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[3] = {}
			return function()
				reliable_events[3] = nil
			end
		end,
	},
	ServerLookVectorReplicated = {
		SetCallback = function(Callback: (Value: ({
			["player"]: (Player),
			["lookDirection"]: (Vector3),
			["componentName"]: (string),
			})) -> ()): () -> ()
			unreliable_events[3] = Callback
			for _, value in unreliable_event_queue[3] do
				task.spawn(Callback, value)
			end
			unreliable_event_queue[3] = {}
			return function()
				unreliable_events[3] = nil
			end
		end,
	},
	RoundStatsComponentReplicator = {
		On = function(Callback: (Value: ({ [(Player)]: ((unknown)) })) -> ())
			table.insert(reliable_events[23], Callback)
			for _, value in reliable_event_queue[23] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[23] = {}
			return function()
				table.remove(reliable_events[23], table.find(reliable_events[23], Callback))
			end
		end,
	},
	RespondPlayersInHitbox = {
		Fire = function(Value: ({ ((Player)?) }))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 5)
			local len_26 = #Value
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_26)
			for i_5 = 1, len_26 do
				local bool_27 = 0
				local bool_27_pos_1 = alloc(1)
				local val_6 = Value[i_5]
				if val_6 ~= nil then
					bool_27 = bit32.bor(bool_27, 0b0000000000000001)
					assert(val_6:IsA("Player"), "received instance is not of the Player class!")
					table.insert(outgoing_inst, val_6)
				end
				buffer.writeu8(outgoing_buff, bool_27_pos_1, bool_27)
			end
		end,
	},
	RequestPlayersInHitbox = {
		SetCallback = function(Callback: (Value: ({
			["Type"]: ("Box" | "Sphere"),
			["Size"]: ((unknown)),
			["Offset"]: (Vector3),
			})) -> ()): () -> ()
			reliable_events[8] = Callback
			for _, value in reliable_event_queue[8] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[8] = {}
			return function()
				reliable_events[8] = nil
			end
		end,
	},
	ReplicateItemServer = {
		SetCallback = function(Callback: (Value: ({
			["instance"]: (Tool),
			["destroyed"]: (boolean),
			["constructor"]: (string),
			})) -> ()): () -> ()
			reliable_events[10] = Callback
			for _, value in reliable_event_queue[10] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[10] = {}
			return function()
				reliable_events[10] = nil
			end
		end,
	},
	ReliableComponentNetworkServer = {
		Fire = function(Value: ((unknown)))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			local bool_28 = 0
			local bool_28_pos_1 = alloc(1)
			if Value ~= nil then
				bool_28 = bit32.bor(bool_28, 0b0000000000000001)
				table.insert(outgoing_inst, Value)
			end
			buffer.writeu8(outgoing_buff, bool_28_pos_1, bool_28)
		end,
	},
	ReliableComponentNetworkClient = {
		On = function(Callback: (Value: ((unknown))) -> ())
			table.insert(reliable_events[6], Callback)
			for _, value in reliable_event_queue[6] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[6] = {}
			return function()
				table.remove(reliable_events[6], table.find(reliable_events[6], Callback))
			end
		end,
	},
	RebuildRoleConfigClient = {
		SetCallback = function(Callback: (Value: ({
			["player"]: (Player),
			["params"]: ({
				["Role"]: (string),
				["Skin"]: ((string)?),
				["Character"]: ((string)?),
			}),
			})) -> ()): () -> ()
			reliable_events[2] = Callback
			for _, value in reliable_event_queue[2] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[2] = {}
			return function()
				reliable_events[2] = nil
			end
		end,
	},
	PointsAwarded = {
		On = function(Callback: (Value: ({
			["amount"]: (number),
			["actionId"]: ((number)?),
			["message"]: ((string)?),
			})) -> ())
			table.insert(reliable_events[14], Callback)
			for _, value in reliable_event_queue[14] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[14] = {}
			return function()
				table.remove(reliable_events[14], table.find(reliable_events[14], Callback))
			end
		end,
	},
	PlayerDied = {
		On = function(Callback: (Value: ({
			["player"]: (Player),
			["killers"]: (({ (Player) })?),
			})) -> ())
			table.insert(reliable_events[13], Callback)
			for _, value in reliable_event_queue[13] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[13] = {}
			return function()
				table.remove(reliable_events[13], table.find(reliable_events[13], Callback))
			end
		end,
	},
	PlayerActionApplied = {
		SetCallback = function(Callback: (Value: (string)) -> ()): () -> ()
			unreliable_events[1] = Callback
			for _, value in unreliable_event_queue[1] do
				task.spawn(Callback, value)
			end
			unreliable_event_queue[1] = {}
			return function()
				unreliable_events[1] = nil
			end
		end,
	},
	OnServerInventoryToggle = {
		SetCallback = function(Callback: (Value: (boolean)) -> ()): () -> ()
			reliable_events[9] = Callback
			for _, value in reliable_event_queue[9] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[9] = {}
			return function()
				reliable_events[9] = nil
			end
		end,
	},
	ObjectivesChanged = {
		SetCallback = function(Callback: (Value: ({
			["amount"]: (number),
			["solvedAmount"]: (number),
			})) -> ()): () -> ()
			reliable_events[20] = Callback
			for _, value in reliable_event_queue[20] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[20] = {}
			return function()
				reliable_events[20] = nil
			end
		end,
	},
	MatchServiceStartLMS = {
		On = function(Callback: (Value: ((unknown))) -> ())
			table.insert(reliable_events[15], Callback)
			for _, value in reliable_event_queue[15] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[15] = {}
			return function()
				table.remove(reliable_events[15], table.find(reliable_events[15], Callback))
			end
		end,
	},
	MatchServiceSetPreparing = {
		SetCallback = function(Callback: (Value: (boolean)) -> ()): () -> ()
			reliable_events[19] = Callback
			for _, value in reliable_event_queue[19] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[19] = {}
			return function()
				reliable_events[19] = nil
			end
		end,
	},
	MatchServiceSetMatchState = {
		SetCallback = function(Callback: (Value: ({
			["name"]: (string),
			["ended"]: (boolean),
			["duration"]: (number),
			})) -> ()): () -> ()
			reliable_events[17] = Callback
			for _, value in reliable_event_queue[17] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[17] = {}
			return function()
				reliable_events[17] = nil
			end
		end,
	},
	MatchServiceSetMap = {
		On = function(Callback: (Value: (string)) -> ())
			table.insert(reliable_events[16], Callback)
			for _, value in reliable_event_queue[16] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[16] = {}
			return function()
				table.remove(reliable_events[16], table.find(reliable_events[16], Callback))
			end
		end,
	},
	MatchServiceCountdownChanged = {
		SetCallback = function(Callback: (Value: ({
			["value"]: (number),
			["reason"]: ((string)?),
			})) -> ()): () -> ()
			reliable_events[18] = Callback
			for _, value in reliable_event_queue[18] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[18] = {}
			return function()
				reliable_events[18] = nil
			end
		end,
	},
	LoadedConfirmed = {
		SetCallback = function(Callback: (Value: ((unknown))) -> ()): () -> ()
			reliable_events[0] = Callback
			for _, value in reliable_event_queue[0] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[0] = {}
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	Loaded = {
		Fire = function(Value: ((unknown)))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local bool_29 = 0
			local bool_29_pos_1 = alloc(1)
			if Value ~= nil then
				bool_29 = bit32.bor(bool_29, 0b0000000000000001)
				table.insert(outgoing_inst, Value)
			end
			buffer.writeu8(outgoing_buff, bool_29_pos_1, bool_29)
		end,
	},
	InventoryComponentDropItemServer = {
		Fire = function(Value: (Tool))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 6)
			assert(Value:IsA("Tool"), "received instance is not of the Tool class!")
			table.insert(outgoing_inst, Value)
		end,
	},
	HideoutLeavePrompt = {
		Fire = function(Value: ((unknown)))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 7)
			local bool_30 = 0
			local bool_30_pos_1 = alloc(1)
			if Value ~= nil then
				bool_30 = bit32.bor(bool_30, 0b0000000000000001)
				table.insert(outgoing_inst, Value)
			end
			buffer.writeu8(outgoing_buff, bool_30_pos_1, bool_30)
		end,
	},
	Dispatch = {
		SetCallback = function(Callback: (Value: ({ ({
			["name"]: (string),
			["arguments"]: ({ ((unknown)) }),
			}) })) -> ()): () -> ()
			reliable_events[1] = Callback
			for _, value in reliable_event_queue[1] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[1] = {}
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	DespawnRequest = {
		Fire = function(Value: ((unknown)))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local bool_31 = 0
			local bool_31_pos_1 = alloc(1)
			if Value ~= nil then
				bool_31 = bit32.bor(bool_31, 0b0000000000000001)
				table.insert(outgoing_inst, Value)
			end
			buffer.writeu8(outgoing_buff, bool_31_pos_1, bool_31)
		end,
	},
	DamageTaken = {
		On = function(Callback: (Value: ({
			["player"]: (Player),
			["damager"]: ((Player)?),
			["origin"]: ((Vector3)?),
			["damage"]: (number),
			["source"]: ((string)?),
			})) -> ())
			table.insert(reliable_events[12], Callback)
			for _, value in reliable_event_queue[12] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[12] = {}
			return function()
				table.remove(reliable_events[12], table.find(reliable_events[12], Callback))
			end
		end,
	},
	ComponentReplicatorClient = {
		SetCallback = function(Callback: (Value: ((unknown))) -> ()): () -> ()
			reliable_events[7] = Callback
			for _, value in reliable_event_queue[7] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[7] = {}
			return function()
				reliable_events[7] = nil
			end
		end,
	},
	ClientTRStateChanged = {
		Fire = function(Value: (number))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 10)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value)
		end,
	},
	ClientSettingSaveRequest = {
		Fire = function(Value: ({ [(string)]: ((unknown)) }))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 8)
			local bool_32 = 0
			local bool_32_pos_1 = alloc(1)
			local len_pos_1
			local len_27 = 0
			for k_1, v_1 in Value do
				if len_27 == 0 then
					len_pos_1 = alloc(2)
				end
				local bool_33 = 0
				local bool_33_pos_1 = alloc(1)
				len_27 = len_27 + 1
				local len_28 = #k_1
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_28)
				alloc(len_28)
				buffer.writestring(outgoing_buff, outgoing_apos, k_1, len_28)
				if v_1 ~= nil then
					bool_33 = bit32.bor(bool_33, 0b0000000000000001)
					table.insert(outgoing_inst, v_1)
				end
				buffer.writeu8(outgoing_buff, bool_33_pos_1, bool_33)
			end
			if len_pos_1 then
				buffer.writeu16(outgoing_buff, len_pos_1, len_27 - 1)
			else
				bool_32 = bit32.bor(bool_32, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_32_pos_1, bool_32)
		end,
	},
	ClientLookVectorChanged = {
		Fire = function(Value: (Vector3))
			local saved = save()
			load_empty()
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value.X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value.Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value.Z)
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			unreliable[3]:FireServer(buff, outgoing_inst)
			load(saved)
		end,
	},
	ClientLanded = {
		Fire = function(Value: ({
			["StarterHeight"]: (number),
			["EndHeight"]: (number),
			}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 12)
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["StarterHeight"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["EndHeight"])
		end,
	},
	ClientFallStarted = {
		Fire = function(Value: (number))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 11)
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value)
		end,
	},
	ClientChaseStateChanged = {
		Fire = function(Value: (boolean))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 9)
			local bool_34 = 0
			local bool_34_pos_1 = alloc(1)
			if Value then
				bool_34 = bit32.bor(bool_34, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_34_pos_1, bool_34)
		end,
	},
	CharacterSyncFromServer = {
		SetCallback = function(Callback: (Value: ({
			["player"]: (Player),
			["part"]: (Part),
			["cframe"]: (CFrame),
			})) -> ()): () -> ()
			unreliable_events[2] = Callback
			for _, value in unreliable_event_queue[2] do
				task.spawn(Callback, value)
			end
			unreliable_event_queue[2] = {}
			return function()
				unreliable_events[2] = nil
			end
		end,
	},
	CharacterSyncFromClient = {
		Fire = function(Value: ({
			["part"]: (Part),
			["cframe"]: (CFrame),
			}))
			local saved = save()
			load_empty()
			assert(Value["part"]:IsA("Part"), "received instance is not of the Part class!")
			table.insert(outgoing_inst, Value["part"])
			local axis_1, angle_2 = Value["cframe"]:ToAxisAngle()
			axis_1 = axis_1 * angle_2
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["cframe"].Position.X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["cframe"].Position.Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["cframe"].Position.Z)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, axis_1.X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, axis_1.Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, axis_1.Z)
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			unreliable[2]:FireServer(buff, outgoing_inst)
			load(saved)
		end,
	},
	ChangeStamina = {
		On = function(Callback: (Value: ({
			["method"]: ("Set" | "Multiply" | "Increment"),
			["value"]: (number),
			})) -> ())
			table.insert(reliable_events[5], Callback)
			for _, value in reliable_event_queue[5] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[5] = {}
			return function()
				table.remove(reliable_events[5], table.find(reliable_events[5], Callback))
			end
		end,
	},
	ApplyImpulse = {
		SetCallback = function(Callback: (Value: ({
			["part"]: (Instance),
			["impulse"]: (Vector3),
			["isAngular"]: ((boolean)?),
			})) -> ()): () -> ()
			reliable_events[4] = Callback
			for _, value in reliable_event_queue[4] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[4] = {}
			return function()
				reliable_events[4] = nil
			end
		end,
	},
}
type Events = typeof(returns)
return returns
